apiVersion: v2
name: velociraptor
description: A Helm chart for deploying Velociraptor DFIR platform on Kubernetes
type: application
version: 5.0.0
appVersion: "0.7.0"
home: https://github.com/Velocidex/velociraptor
sources:
  - https://github.com/Velocidex/velociraptor
  - https://github.com/your-org/velociraptor-setup-scripts
maintainers:
  - name: Velociraptor Team
    email: support@velocidex.com
keywords:
  - dfir
  - forensics
  - incident-response
  - security
  - monitoring
  - threat-hunting
annotations:
  category: Security
  licenses: AGPL-3.0
dependencies:
  - name: postgresql
    version: "12.1.9"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.3.7"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: "15.18.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.50.7"
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
  - name: elasticsearch
    version: "19.5.0"
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: jaeger
    version: "0.69.1"
    repository: https://jaegertracing.github.io/helm-charts
    condition: tracing.jaeger.enabled