#
# Module manifest for module 'ZeroTrustSecurity'
#
# Generated by: Velociraptor Community
#
# Generated on: 8/20/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ZeroTrustSecurity.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'e7b3c1d2-8f4a-4e9d-b2c1-7f8e3a5d9c2b'

# Author of this module
Author = 'Velociraptor Community'

# Company or vendor of this module
CompanyName = 'Velociraptor DFIR Community'

# Copyright statement for this module
Copyright = '(c) Velociraptor Community. All rights reserved.'

# Description of the functionality provided by this module
Description = @'
Zero-Trust Security Framework for Velociraptor DFIR Infrastructure

This module provides comprehensive zero-trust security implementation for Velociraptor deployments including:
- Network segmentation and micro-segmentation
- Identity and access management with multi-factor authentication
- Certificate-based authentication framework
- Encryption at rest and in transit
- Continuous monitoring and verification
- Least privilege access controls
- Security policy templates and compliance frameworks

Designed for enterprise-grade DFIR operations while maintaining forensic integrity and compliance requirements.
'@

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    @{ModuleName = 'VelociraptorDeployment'; ModuleVersion = '1.0.0'}
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    # Core Zero-Trust Functions
    'Initialize-ZeroTrustSecurity',
    'Test-ZeroTrustCompliance',
    'Enable-ZeroTrustMode',
    'Set-ZeroTrustPolicy',
    
    # Network Segmentation
    'New-NetworkSegment',
    'Set-MicroSegmentation',
    'Test-NetworkIsolation',
    'Get-NetworkTrustBoundaries',
    
    # Identity and Access Management
    'New-ZeroTrustIdentity',
    'Set-MultiFactorAuthentication',
    'Test-IdentityVerification',
    'Invoke-ContinuousAuthentication',
    
    # Certificate Management
    'New-ZeroTrustCertificate',
    'Set-CertificateBasedAuth',
    'Test-CertificateChain',
    'Revoke-ZeroTrustCertificate',
    
    # Encryption Framework
    'Enable-EndToEndEncryption',
    'Set-EncryptionAtRest',
    'Test-EncryptionCompliance',
    'Rotate-EncryptionKeys',
    
    # Continuous Monitoring
    'Start-ZeroTrustMonitoring',
    'Test-ContinuousVerification',
    'Get-SecurityTelemetry',
    'Invoke-ThreatDetection',
    
    # Access Controls
    'Set-LeastPrivilegeAccess',
    'Test-PrivilegeEscalation',
    'Invoke-JustInTimeAccess',
    'Set-ConditionalAccess',
    
    # Policy Management
    'Import-ZeroTrustPolicy',
    'Export-ZeroTrustPolicy',
    'Test-PolicyCompliance',
    'Set-ComplianceFramework',
    
    # Cloud Zero-Trust
    'Set-CloudZeroTrust',
    'Enable-CloudSecurityPosture',
    'Test-CloudCompliance',
    
    # Container Security
    'Set-ContainerZeroTrust',
    'Enable-PodSecurityPolicy',
    'Test-ContainerIsolation'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @(
    'zt-init',
    'zt-test',
    'zt-enable',
    'zt-monitor',
    'zt-verify'
)

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'ZeroTrustSecurity.psm1',
    'ZeroTrustSecurity.psd1',
    'functions\Core-ZeroTrust.ps1',
    'functions\Network-Segmentation.ps1',
    'functions\Identity-AccessManagement.ps1',
    'functions\Certificate-Management.ps1',
    'functions\Encryption-Framework.ps1',
    'functions\Continuous-Monitoring.ps1',
    'functions\Access-Controls.ps1',
    'functions\Policy-Management.ps1',
    'functions\Cloud-ZeroTrust.ps1',
    'functions\Container-Security.ps1',
    'templates\zero-trust-policies.json',
    'templates\network-segmentation.yaml',
    'templates\compliance-frameworks.json'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('ZeroTrust', 'Security', 'DFIR', 'Velociraptor', 'NetworkSecurity', 'IAM', 'Encryption', 'Compliance', 'Monitoring', 'AccessControl')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/Velocidex/velociraptor/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Velocidex/velociraptor'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
Zero-Trust Security Framework v1.0.0

Initial release featuring:
- Comprehensive zero-trust architecture implementation
- Network micro-segmentation with trust boundaries
- Multi-factor authentication and continuous verification
- Certificate-based authentication framework
- End-to-end encryption with key rotation
- Real-time security monitoring and threat detection
- Least privilege access controls with JIT access
- Policy-driven compliance framework
- Multi-cloud zero-trust configurations
- Container and Kubernetes security policies

Designed specifically for DFIR operations while maintaining forensic integrity.
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}