#
# Module manifest for module 'VelociraptorCompliance'
#
# Generated by: Velociraptor Community
#
# Generated on: 8/20/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'VelociraptorCompliance.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c'

# Author of this module
Author = 'Velociraptor Community'

# Company or vendor of this module
CompanyName = 'Velociraptor DFIR Community'

# Copyright statement for this module
Copyright = '(c) 2025 Velociraptor Community. All rights reserved.'

# Description of the functionality provided by this module
Description = @'
Enterprise Compliance Framework for Velociraptor DFIR Infrastructure

This module provides comprehensive compliance capabilities for Velociraptor deployments including:
- FedRAMP, SOC2, ISO27001, NIST, HIPAA, PCI-DSS, and GDPR framework support
- Automated compliance assessment and validation
- Continuous compliance monitoring with real-time alerting
- Forensically sound audit trail generation and evidence collection
- Enterprise-grade compliance reporting and documentation
- Integration with existing Velociraptor deployment workflows
- Compliance control mapping and gap analysis
- Risk assessment and remediation tracking

Designed specifically for enterprise DFIR operations while maintaining forensic integrity
and supporting regulatory compliance requirements across multiple frameworks.
'@

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    @{ModuleName = 'VelociraptorDeployment'; ModuleVersion = '5.0.4'}
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    # Core Compliance Functions
    'Initialize-VelociraptorCompliance',
    'Test-VelociraptorCompliance',
    'Enable-VelociraptorComplianceMonitoring',
    'Disable-VelociraptorComplianceMonitoring',
    'Get-VelociraptorComplianceStatus',
    'Set-VelociraptorComplianceConfiguration',
    
    # Framework-Specific Functions
    'Test-VelociraptorFedRAMP',
    'Test-VelociraptorSOC2',
    'Test-VelociraptorISO27001',
    'Test-VelociraptorNIST',
    'Test-VelociraptorHIPAA',
    'Test-VelociraptorPCIDSS',
    'Test-VelociraptorGDPR',
    
    # Audit and Evidence Functions
    'Write-VelociraptorComplianceAudit',
    'Get-VelociraptorComplianceAuditLog',
    'New-VelociraptorComplianceEvidence',
    'Export-VelociraptorComplianceEvidence',
    'Import-VelociraptorComplianceEvidence',
    'Test-VelociraptorComplianceEvidence',
    
    # Assessment and Reporting Functions
    'Start-VelociraptorComplianceAssessment',
    'Get-VelociraptorComplianceAssessment',
    'Export-VelociraptorComplianceReport',
    'New-VelociraptorComplianceRecommendations',
    'Get-VelociraptorComplianceGaps',
    
    # Control Management Functions
    'Get-VelociraptorComplianceControls',
    'Test-VelociraptorComplianceControl',
    'Set-VelociraptorComplianceControl',
    'Import-VelociraptorComplianceControls',
    'Export-VelociraptorComplianceControls',
    
    # Risk Management Functions
    'Start-VelociraptorRiskAssessment',
    'Get-VelociraptorRiskRegister',
    'Set-VelociraptorRiskMitigation',
    'Test-VelociraptorRiskControls',
    
    # Continuous Monitoring Functions
    'Start-VelociraptorComplianceMonitor',
    'Stop-VelociraptorComplianceMonitor',
    'Get-VelociraptorComplianceAlerts',
    'Set-VelociraptorComplianceThresholds',
    
    # Integration and Workflow Functions
    'Register-VelociraptorComplianceWorkflow',
    'Invoke-VelociraptorComplianceWorkflow',
    'Test-VelociraptorComplianceIntegration',
    
    # Template and Configuration Functions
    'Get-VelociraptorComplianceTemplate',
    'New-VelociraptorComplianceTemplate',
    'Import-VelociraptorComplianceTemplate',
    'Export-VelociraptorComplianceTemplate',
    
    # Remediation Functions
    'Get-VelociraptorComplianceRemediation',
    'Start-VelociraptorComplianceRemediation',
    'Test-VelociraptorComplianceRemediation',
    'Export-VelociraptorRemediationPlan'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @(
    # Short aliases for common compliance operations
    'Init-Compliance',
    'Test-Compliance',
    'Enable-ComplianceMonitoring',
    'Get-ComplianceStatus',
    'Start-ComplianceAssessment',
    'Export-ComplianceReport',
    
    # Framework-specific aliases
    'Test-FedRAMP',
    'Test-SOC2',
    'Test-ISO27001',
    'Test-NIST',
    'Test-HIPAA',
    'Test-PCIDSS',
    'Test-GDPR',
    
    # Audit aliases
    'Audit-Log',
    'Compliance-Audit',
    'Evidence-Export',
    
    # Monitoring aliases
    'Start-Monitor',
    'Stop-Monitor',
    'Get-Alerts'
)

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'VelociraptorCompliance.psm1',
    'VelociraptorCompliance.psd1',
    'functions\Core-Compliance.ps1',
    'functions\Framework-Specific.ps1', 
    'functions\Audit-Evidence.ps1',
    'functions\Assessment-Reporting.ps1',
    'functions\Control-Management.ps1',
    'functions\Risk-Management.ps1',
    'functions\Continuous-Monitoring.ps1',
    'functions\Integration-Workflows.ps1',
    'functions\Template-Configuration.ps1',
    'functions\Remediation-Functions.ps1',
    'templates\FedRAMP-controls.json',
    'templates\SOC2-controls.json',
    'templates\ISO27001-controls.json',
    'templates\NIST-controls.json',
    'templates\HIPAA-controls.json',
    'templates\PCI-DSS-controls.json',
    'templates\GDPR-controls.json',
    'templates\compliance-configuration.yaml',
    'templates\assessment-templates.json',
    'templates\evidence-templates.json',
    'schemas\compliance-schema.json',
    'schemas\assessment-schema.json',
    'schemas\evidence-schema.json'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Compliance', 'FedRAMP', 'SOC2', 'ISO27001', 'NIST', 'HIPAA', 'PCI-DSS', 'GDPR', 'DFIR', 'Velociraptor', 'Security', 'Audit', 'Governance', 'Risk', 'Enterprise', 'Forensics')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/Ununp3ntium115/Velociraptor_Setup_Scripts/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Ununp3ntium115/Velociraptor_Setup_Scripts'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
Velociraptor Compliance Framework v1.0.0

Initial release featuring comprehensive enterprise compliance capabilities:

## Core Features
- Multi-framework compliance support (FedRAMP, SOC2, ISO27001, NIST, HIPAA, PCI-DSS, GDPR)
- Automated compliance assessment with detailed scoring and gap analysis
- Continuous compliance monitoring with real-time alerting and threshold management
- Forensically sound audit trail generation with tamper-evident logging
- Enterprise-grade evidence collection and chain of custody management

## Assessment and Reporting
- Comprehensive compliance assessments with control-level testing
- Multiple output formats (JSON, XML, HTML, CSV) for assessment reports
- Risk assessment and mitigation tracking with automated recommendations
- Compliance dashboard and executive reporting capabilities
- Gap analysis with prioritized remediation plans

## Monitoring and Alerting
- Real-time compliance monitoring with configurable intervals
- Automated alerting for compliance violations and threshold breaches
- Trend analysis and compliance score tracking over time
- Integration with existing SIEM and monitoring infrastructure
- Predictive compliance analytics and early warning systems

## Framework Support
- FedRAMP Low/Moderate/High authorization levels with 800+ controls
- SOC2 Type I/II with all Trust Service Categories (Security, Availability, etc.)
- ISO27001:2013 with full Annex A control set implementation
- NIST Cybersecurity Framework with all five functions
- HIPAA Security Rule compliance with administrative, physical, and technical safeguards
- PCI-DSS v4.0 with all six control objectives for card data protection
- GDPR compliance with privacy by design and data protection impact assessments

## Integration and Automation
- Seamless integration with existing Velociraptor deployment workflows
- PowerShell Desired State Configuration (DSC) support for compliance automation
- REST API integration for external compliance management systems
- CI/CD pipeline integration for DevSecOps compliance workflows
- Custom workflow orchestration with approval processes

## Evidence and Audit Management
- Automated evidence collection with cryptographic integrity verification
- Chain of custody tracking for forensic admissibility
- Evidence packaging and export for external auditors
- Compliance artifact management with version control
- Audit log analysis and compliance trend reporting

## Enterprise Features
- Multi-tenant compliance management for large organizations
- Role-based access control (RBAC) for compliance administrators
- Compliance dashboard with executive and operational views
- Integration with enterprise identity providers (Active Directory, Azure AD)
- Scalable architecture supporting thousands of endpoints

Designed specifically for enterprise DFIR operations while maintaining the project's
mission of democratizing professional-grade security tools for all incident responders.
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}